### ISSUE TITLE
Nutze bisherigen GH-Pages-Branch beim Deployen?

### ISSUE THREAD

**Issue by cagix** [Compilerbau/Lecture#18]
Derzeit wird beim Deployen durch die GH-Action immer ein neuer Branch `gh-pages` erzeugt und die Inhalte des angegebenen Ordners (im Beispiel `docs/`) dort hochgeladen.

```yaml
- uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_branch: gh-pages
    publish_dir: docs/
    force_orphan: true
```

Der Workflow von @bcg7 sieht vor, dass aus den Markdownquellen jeweils ein Foliensatz und die entsprechende Webseite generiert werden. Im Markdown der Seite würde sie einen festen Link auf ein PDF in einem Unterordner der Seite einbauen, welches zum Zeitpunkt des Bauens noch nicht existiert (und im `master` nie existieren wird). Die generierten Folien würde sie dann im `gh-pages`-Branch an der richtigen Stelle in der Ordnerhierarchie einchecken, damit die Studierenden in der Webseite auf den Link klicken können und den Foliensatz angezeigt bekommen. Nach der Vorlesung möchte sie den alten Foliensatz mit dem neuen annotierten Foliensatz ersetzen (wieder im `gh-pages`-Branch).

Dieser Workflow funktioniert nur, wenn `peaceiris/actions-gh-pages` es erlaubt, den neuen Hugo-Build über den letzten zu committen und nicht jedes Mal einen neuen Branch zu erzeugen. 

@jposselt @AMatutat Könnt ihr das bitte mal ausprobieren?
